# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME = 'sportSchedule'
      DATABASE_USER = 'vinz'
      DATABASE_PASS = 'vinzvinzvinz'
      DATABASE_URI = 'mongodb://database:27017/sportSchedule'
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: vinz
      MONGO_INITDB_ROOT_PASSWORD: vinzvinzvinz